language: python
python:
  - "2.7"
  - "3.5"
  - "3.8"
  - "3.8-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

install:
  - pip install pytest

script:
  - pytest
